export const FETCH_EVENTS = 'FETCH_EVENTS'
export const CREATE_EVENT = 'CREATE_EVENT'
//
export const ATTEMPT_LOGIN = 'ATTEMPT_LOGIN'
export const ATTEMPT_REGISTER = 'ATTEMPT_REGISTER'
//
export const WINDOW_RESIZE = 'WINDOW_RESIZE'
//
export const SEARCH_BY_CITY = 'SEARCH_BY_CITY'